server {
    listen 80;
    server_name _;

    # frontend
    root /home/admin/Programs/Raspberry/front/dist; 
    index index.html;

    location / {
        # Якщо файл не знайдено — віддаємо index.html
        try_files $uri $uri/ /index.html;
    }

    # Proxy API for С++ back
    location /api/ {
        proxy_pass http://127.0.0.1:1616; # Prot of backand
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy /ping 
    location /ping {
        proxy_pass http://127.0.0.1:1616/ping;
    }
}