[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
upload_protocol = stlink
upload_tool = stlink

; upload_flags = 
;   -c
  ; set CPUTAPID 0x2ba01477 0x1ba01477
  ; set CPUTAPID   0x2ba01477

build_flags =
    -Wl,-u,_printf_float
    -Wl,-u,_scanf_float
    -std=c99