db_login="home_server"
db_open_password="psql"
db_name="home_server_db"
table_name="test_table"
FIREBASE_URL="https://home-server-9e586-default-rtdb.firebaseio.com/measurements.json?auth=eOpdxQjllRN3hJ2Z9bIag33HIC2LaU97GkyBRvXG"


